@echo off
echo Starting Crypto Trader...
echo.
echo Starting backend on port 3001...
start "Backend" cmd /k "cd /d %~dp0server && npm run dev"
echo.
echo Waiting 3 seconds for backend...
timeout /t 3 /nobreak > nul
echo.
echo Starting frontend on port 5173...
start "Frontend" cmd /k "cd /d %~dp0client && npm run dev"
echo.
echo Open http://localhost:5173 in your browser
echo Press any key to exit...
pause
